const types = {
  GET_AUTH_LINK_REQUEST: 'GET_AUTH_LINK_REQUEST',
  GET_AUTH_LINK_SUCCESS: 'GET_AUTH_LINK_SUCCESS',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',

  AUTO_SIGN_IN_REQUEST: 'AUTO_SIGN_IN_REQUEST',

  GET_REPORTS_REQUEST: 'GET_REPORTS_REQUEST',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',

  SELECT_REPORT_REQUEST: 'SELECT_REPORT_REQUEST',
  SELECT_REPORT_SUCCESS: 'SELECT_REPORT_SUCCESS',
};

export default types;